#ifndef TAPI_LLVM_OBJECT_MACHO_H_
#define TAPI_LLVM_OBJECT_MACHO_H_

#define PLATFORM_IOSSIMULATOR MISSING_PLATFORM_IOSSIMULATOR
#define PLATFORM_TVOSSIMULATOR MISSING_PLATFORM_TVOSSIMULATOR
#define PLATFORM_WATCHOSSIMULATOR MISSING_PLATFORM_WATCHOSSIMULATOR

#include_next <llvm/Object/MachO.h>

#undef PLATFORM_IOSSIMULATOR
#undef PLATFORM_TVOSSIMULATOR
#undef PLATFORM_WATCHOSSIMULATOR

#endif // TAPI_LLVM_OBJECT_MACHO_H_
