[package]
name = "app-store-connect"
version = "0.5.0"
edition = "2021"
rust-version = "1.70"
license = "Apache-2.0 OR MIT"
description = "Apple App Store Connect API and client"
keywords = ["apple"]
homepage = "https://github.com/indygreg/apple-platform-rs"
repository = "https://github.com/indygreg/apple-platform-rs.git"
readme = "README.md"

[dependencies]
anyhow = "1.0.79"
base64 = "0.21.7"
clap = { version = "4.4.17", features = ["derive"] }
dirs = "5.0.1"
env_logger = "0.10.1"
jsonwebtoken = "9.2.0"
log = "0.4.20"
pem = "3.0.3"
rand = "0.8.5"
reqwest = { version = "0.11.23", default-features = false, features = ["blocking", "json", "rustls-tls-native-roots"] }
rsa = "0.9.6"
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
thiserror = "1.0.56"
x509-certificate = "0.23.1"
