jobs:
- job: linux
  timeoutInMinutes: 300
  pool:
    vmImage: 'Ubuntu-latest'
  steps:
  - script:
      cmake -E make_directory cmake-build-azure
    displayName: Prepare project
  - script:
      cmake -E chdir cmake-build-azure cmake ..
      -DCMAKE_BUILD_TYPE=Release
      -DCMAKE_C_COMPILER=clang
      -DCMAKE_CXX_COMPILER=clang++
      -DCMAKE_INSTALL_PREFIX="$(Build.ArtifactStagingDirectory)"
    displayName: Configure project
  - script:
      cmake --build cmake-build-azure --target installation -- -j 4
    displayName: Build project
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'wimal'
    displayName: Upload artifact
