on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:
  schedule:
    - cron: '12 15 * * *'
  workflow_dispatch:
jobs:
  build-and-test:
    uses: indygreg/actions/.github/workflows/rust-workspace-build-and-test.yml@214a8641784d19c45f4261ed8e5a57db81ae6b4e
    with:
      actions_ref: "214a8641784d19c45f4261ed8e5a57db81ae6b4e"
      msrv: "1.70.0"
      sccache_s3_bucket: apple-platform-rs-sccache
      no_default_features: true
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
